name: signac_sat
description: Package para a criação da assinatura SignAC para equipamentos SAT
version: 1.0.1
repository: https://github.com/brasizza/signac_sat-package-dart
false_secrets:
  - /example/signac_sat_example.dart
  - /test/signac_sat_test.dart
environment:
  sdk: ^3.0.5



# Add regular dependencies here.
dependencies:
  encrypt: ^5.0.3
  pointycastle: ^3.7.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
